### ISSUE TITLE
Request: Adapt Pop!_OS 20.04 LVM-luks tutorial for use it with ext4 filesytem

### ISSUE THREAD

**Issue by Skabit** [wmutschl/mutschler.eu#16]
Hi Willi,

I want to encrypt a new installation of Pop!_OS 20.04, but I'm newbie. I follow [your tutorial ](https://mutschler.eu/linux/install-guides/pop-os-btrfs/)about Pop_OS and btrfs filesystem but I have a classic HDD and I prefer the ext4 filesystem with a traditional partitions (root, swap and home). Following your instructions I can understand something but in the middle I can't continue. Now, I write my process and maybe with your help the initial tutorial can expand for users of ext4, in particular that don't exist tutorials about installation of encrypted full disk with Pop!_OS.

1. Reading about LUKS and LVM one thing is clear: GRUB don't boot with LUKS1, but in your text you wrote that Pop!_OS 20.04 can boot with LUKS2: `Pop!_OS uses the systemd bootloader, which can handle luks type 2 encryption just fine at boot time`

2. First step is load live USB. Then I use Gparted and created a partition table and layout

-  gpt
-  a 512 MB EFI (fat32)
-  rest of disk without format
- apply changes and tick a efi partition with `boot` and `esp` flags.

3. Then create a LUKS partition:

```
cryptsetup luksFormat /dev/sda2
cryptsetup luksOpen /dev/sda2 cryptdata
```
```
pvcreate /dev/mapper/cryptdata
vgcreate data /dev/mapper/cryptdata
```
```
lvcreate -n swap -L 8G data
lvcreate -n root -L 30G data
lvcreate -n home -L 100%FREE data
```
* Note: This scheme is similar to [arch wiki](https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#LUKS_on_LVM) example.

4.  Next, I will use the Pop!_OS installer to format the partitions and install system, but in this moment I can't continue, because I don't understand your process. 

**Request:**

I read your tutorial about [Ubuntu and btrfs-luks](https://mutschler.eu/linux/install-guides/ubuntu-btrfs/), where you don't restart the OS, you return to terminal and write some commands for finish the process. For complete this new version of your tutorial about Pop!_OS we need that you complete the commands for finish the installation process. So we need the **post-installation steps** for ext4 filesystem.

Additionally, in the Pop!_OS tutorial you don't mention nothing about how to avoid type [passphrase twice](https://mutschler.eu/linux/install-guides/ubuntu-btrfs/#add-a-key-file-to-type-luks-passphrase-only-once-optional-but-recommended). Please don't forget that reference.

Finally, another reference important is about swap. In my proposition the swap is part of encrypted partition so I don't know if is necessary create other encrypted partition.

---

Willi thanks for your time and all your knowledge that you share.

**Comment by wmutschl** [comment]
I think you should simply hit "Clean Install" with encryption in Pop's installer, because this will create almost exactly what you want to achieve (if I understand correctly). You will get a luks2 encrypted ext4 data partition (/boot and /home are inside this partition) and a dedicated 4 GB swap partition that is also encrypted with a different key everytime you reboot.

So what is it exactly, that differs from Pop's default install that you want to achieve?
