### ISSUE TITLE
Missing links on Fedora part

### ISSUE THREAD

**Issue by rimko** [wmutschl/mutschler.eu#18]
Hi, first off thanks for your awesome guide!

I notice the youtube video is missing on ["fedora-btrfs"](https://mutschler.eu/linux/install-guides/fedora-btrfs/), and the page ["fedora-btrfs-raid1"](https://mutschler.eu/linux/install-guides/fedora-btrfs-raid1) is also missing.

**Comment by wmutschl** [comment]
Thanks for pointing this out, unfortunately, I did not have time to do such a video yet, so I updated the post.
