### ISSUE TITLE
Suggestion for an additional, hard-to-miss note for a gotcha than can occur during install for the unwary

### ISSUE THREAD

**Issue by schade** [wmutschl/mutschler.eu#19]
I fixed my error when this occured but showing the user your correct file does not imply strongly enough to add a comma to the line preceding the addition we make in the `/etc/kernelstub/configuration` file for somebody who doesn't work on this stuff all day long. I only included the stack trace at the bottom so others who see this will understand how important missing punctuation is and how hard it can potentially be to troubleshoot for the non-veteran coder.

So to the meat of my issue:
Can you add a bold note when you show that file's correct contents that they also need to add a comma to the end of the line `"splash"` like so `"splash",`?

Other than that I absolutely cannot thank you enough for this document. It scratched an itch I didn't even realize I had.

### **Below added for explanatory purposes:**

Using your `Pop!_OS 21.04: installation guide with btrfs-LVM-luks and auto-apt snapshots with Timeshift` fails at update-initramfs command with the following stack trace:

``` shell
root@pop-os:/# update-initramfs -c -k all
update-initramfs: Generating /boot/initrd.img-5.11.0-7620-generic
kernelstub.Config    : INFO     Looking for configuration...
Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 244, in <module>
    main()
  File "/usr/bin/kernelstub", line 241, in main
    kernelstub.main(args)
  File "/usr/lib/python3/dist-packages/kernelstub/application.py", line 142, in main
    config = Config.Config()
  File "/usr/lib/python3/dist-packages/kernelstub/config.py", line 50, in __init__
    self.config = self.load_config()
  File "/usr/lib/python3/dist-packages/kernelstub/config.py", line 60, in load_config
    self.config = json.load(config_file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 7 (char 363)
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
```

This is running exactly as described in your document (with the slight changes for my partition layout, UUIDs, and such.

**Comment by wmutschl** [comment]
Good point as people tend to oversee this! Fixed in 9237b791ebc65fab00c625b474a858c68ab2a366
