### ISSUE TITLE
Pop!_OS 20.04 Raid1 guide with Pop!_OS 21.04:  btrfs-progs 5.10.1-1 error: no such directory

### ISSUE THREAD

**Issue by pr0nstache** [wmutschl/mutschler.eu#20]
Using the Pop!_OS 20.04-Raid1 guide to install Pop!_OS 21.04, I found an error with `btrfs-progs 5.10.1-1` that is included with the installation media of Pop!_OS 21.04: btrfs-progs throws a "no such directory" error when I get to the line `btrfs device add /dev/mapper/data_vdb-root /mnt`

I solved this by downloading btrfs-progs 5.13.1-1 and then `btrfs device add /dev/mapper/data_vdb-root /mnt` worked just like it should in the guide.  Version 5.13.1-1 isn't really for ubuntu/pop_os and the error for 5.10.1-1 is acknowledged by a forum post that it was fixed in 5.11, but the ppa's only update to 5.10.1-1 for Pop!_OS 21.04.

Anyway, on a testboot there were some errors like the file manager wouldn't load and the system was generally unresponsive.  This was just an initial test on a new media server, to see how the NVME raid would work for the OS disk.  I plan to run the guide again and check my setup more carefully in a text editor and see if it solves the weird login behavior.

Hopefully if you make a Raid1 guide for 21.04 this will save you a step of figuring out why btrfs-progs won't cooperate at `btrfs device add /dev/mapper/data_vdb-root /mnt`

**Comment by wmutschl** [comment]
Hi, funny thing is that I had the same issue a couple of days ago where on a new server I wanted to add another device to the BTRFS RAID1 (I wanted to try out RAID1C4 capabilities, that is having 4 drives in a RAID1); anyways, with version 5.10.1 I also cannot add devices to an already created RAID1 I needed to delete everything and create the RAID1C4 with mkfs.btrfs for all four drives simultaneously. Thanks for pointing out that the updated btrfs-progs version solves this issue, so no need to open a bug report. Where did you download version 5.13.1.?

**Comment by pr0nstache** [comment]
This isn't where (I think) I would get the package from when I finish my server properly, but it came from https://pkgs.org/download/btrfs-progs  I used the Debian-sid amd64 5.13.1-1.  This oddball version could explain my boot issues, or maybe I didn't change a "vda" to "nvme0n1" or "nvme0n1p4" properly.  Great guide though, easy to follow and gave me a lot to think about on the new setup

I didn't mind just using a googled .deb for this run through just to see if the project could continue, I think I'd rather build from their git https://github.com/kdave/btrfs-progs/releases and have it on the ventoy disk when I go through it again.

**Comment by D3v3l0per1** [comment]
Uhm well how do i upgrade the btrfs-progs version in the installer? shoud i just download the package from the github repo or is there a way to do that with apt in the installer? because the links that pr0nstache postet are dead.

**Comment by wmutschl** [comment]
I updated pr0nstache post so that the links will work. So just download the deb file and install it.
