### ISSUE TITLE
broken incomming links

### ISSUE THREAD

**Issue by m10d** [wmutschl/mutschler.eu#26]
Hello, you have some excellent advise around optimization of FDE + btrfs.  I linked here for ubuntu+btrfs-under-luks fde including /boot ... 

I noticed many links to your site are broken on the web as you adjust link names; it makes sense what you changed ( https://web.archive.org/web/*/https://mutschler.eu/linux/install-guides/ubuntu-btrfs --> https://mutschler.eu/linux/install-guides/ubuntu-btrfs-20-04/) HOWEVER I the way your site is laid out I had a bit of a time hooking those up, since you have [thank you btw] many different similar pages.

perhaps consider (at a minimum) keeping old links, and an explanation of how you might change them, or use a naming strategy that lets you keep one un-versioned (latest) link, which redirects to the latest versioned page (which can itself hardlink to past versions at the top)  

anyway, thanks for your resource & efforts.

**Comment by wmutschl** [comment]
Thanks for pointing this out, you make some very valid points which I had not thought about at all! From now on, I try to stick with the above naming scheme, indicating the number of a release, e.g. ubuntu-btrfs-22-04. In any case, I'm now aware to not change the link names!
