### ISSUE TITLE
Fedora install guide zstd version

### ISSUE THREAD

**Issue by Tomptez** [wmutschl/mutschler.eu#28]
First of all, thanks so much for your install guide, it's really useful! One question though: In your [guide](https://github.com/wmutschl/mutschler.eu/blob/main/content/linux/install-guides/fedora-btrfs-35.md) you write 

    compress=zstd: allows to specify the compression algorithm which we want to use. btrfs provides lzo, zstd and zlib  compression algorithms. Based on some Phoronix test cases, zstd seems to be the better performing candidate. Fedora has started to use v1, I will use v3.

Later then you edit `/etc/fstab`

    sed -i 's/compress=zstd:1/ssd,compress=zstd,discard=async/' /etc/fstab

There, you don't specify a zstd version. Shouldn't it be

    sed -i 's/compress=zstd:1/ssd,compress=zstd:3,discard=async/' /etc/fstab

If not, could you please explain why you don't need to specify it but it is still later showing zstd version 3 when you run `mount -v | grep /dev/mapper`

**Comment by wmutschl** [comment]
The default btrfs option is `zstd:3`, so if you don't specify anything it will use version 3. However, Fedora by default uses zstd:1 so I will advise in my future guides to follow Fedora here.
