### ISSUE TITLE
encrypt additional drives in Ubuntu 20.04 using btrfs

### ISSUE THREAD

**Issue by m0nib** [wmutschl/mutschler.eu#29]
Hi,

Thank you for amazingly detailed tutorial for [Ubuntu-btrfs](https://mutschler.eu/linux/install-guides/ubuntu-btrfs-20-04/). 

I do however a couple of questions:
1) After following the tutorial can i add and remove additional drives, I am setting up a work station for data processing. My system "Dell Tower" has bays to slot in and out drives. How will this installation guide affect that, in terms of encryption and mounting drives.
2) could I add another normal user "Not super user" to system and allow the user to carry out tasks but limit them to certain things, such as no internet access and just some specific software on the system.

Thank you if you can get back to me as soon as. As i am in the middle of setting up the work station.

Best regards
Monib

**Comment by wmutschl** [comment]
Hi, sorry for not replying for such a long time. I hope you solved your issues? I do have a guide on how I install my server which also has several drives, so you might find this interesting.
Regarding adding other users: sure, I mean that is exactly one of the things linux excels!
