### ISSUE TITLE
Fix sed command at ubuntu-btrfs-raid1-20-04 installation guide

### ISSUE THREAD

**Issue by amuuza** [wmutschl/mutschler.eu#30]
First of all: thank you very much for such a great guide!!

I installed Trisquel 10 and so far it works great. Except for a couple of little changes to adapt it to Trisquel, I entirely followed your very nice guide.

This issue is about a _sed_ command that needs to be checked. I do not open an issue because I do not dare to fix it myself.

I think the problem came right after you mention "_Also, let’s use UUIDs instead of /dev/mapper/crypt_vda in the fstab_". Then your guide shows the following command:

`sed -i "s|/dev/mapper/crypt_vda|$(blkid -s UUID -o value /dev/mapper/crypt_vda)|" /etc/fstab`

I think it was there when my **fstab** file showed the ID numbers but missed to show "**UUID=**". I had to edit the **fstab** file to add "**UUID=**" right before every ID number, and then everything worked ok.

**Comment by wmutschl** [comment]
Glad to see that the guide also works on other Ubuntu-based systems. I have never tried Trusquel myself but it does look good. sed commands need always to be taken with caution and double check how your fstab looks like after you ran it. When I install my systems I actually seldom use sed commands but do go into the files using an editor and adapt them manually, just to be sure I'm not doing something wrong.
