### ISSUE TITLE
timeshift says "No snapshots found"

### ISSUE THREAD

**Issue by naskya** [wmutschl/mutschler.eu#31]
I'm sorry to open this, but I want your advice to recover my system.

## Question

- I want to restore my system using a snapshot, but I can't do that since my `info.json`s (in my snapshots) are corrupted. Thus, I want to create a valid `info.json` manually and replace it with the corrupted one. What should I write to `info.json`?
- Are there any recommended settings to prevent the corruption of `info.json`?

## Situation

I installed Ubuntu Desktop 21.10 on my machine, following your instruction ([Ubuntu Desktop 20.04: installation guide with btrfs-luks full disk encryption including /boot and auto-apt snapshots with Timeshift](https://mutschler.eu/linux/install-guides/ubuntu-btrfs-20-04/)) last week. The system was stable, and I was very comfortable using it.

However, today I accidentally removed a mandatory package, and my system won't boot properly (it shows GNU GRUB version 2.04 instead).

Then I read your article ([Timeshift (under construction)](https://mutschler.eu/linux/timeshift/)), booted my machine from a Live USB stick, and executed

```bash
$ sudo cryptsetup luksOpen /dev/nvme0n1p3 cryptdata
$ sudo add-apt-repository ppa:teejee2008/timeshift
$ sudo apt update
$ sudo apt install timeshift
```

```
$ sudo timeshift --list --btrfs

/dev/dm-0 is mounted at: /run/timeshift/backup, options: rw,relatime,ssd,space_cache,subvolid=5,subvol=/

E: JSON data must be UTF-8 encoded

(process:8812): Json-CRITICAL **: 02:59:20.107: json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed
E: JSON data must be UTF-8 encoded

(process:8812): Json-CRITICAL **: 02:59:20.108: json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed
E: JSON data must be UTF-8 encoded

[ Omitted since it's massive and repetitive ]

(process:8812): Json-CRITICAL **: 02:59:20.112: json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed
E: JSON data must be UTF-8 encoded

(process:8812): Json-CRITICAL **: 02:59:20.112: json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed
Device : /dev/dm-0 (nvme0n1p3)
UUID   : 17502a7b-cced-4947-9812-ec655bd0c953
Path   : /run/timeshift/backup
Mode   : BTRFS
Status : No snapshots on this device
First snapshot requires: 0 B

No snapshots found
```

... and saw a bunch of errors.

I opened the GUI version of `timeshift` and confirmed that my snapshots are saved, but `info.json`s are corrupted.

![Screenshot from 2022-03-01 03-56-20](https://user-images.githubusercontent.com/48414671/156106954-36b57761-81b9-426a-ac30-64ecb0e796cc.png)

![Screenshot from 2022-03-01 03-58-43](https://user-images.githubusercontent.com/48414671/156106974-73521d3e-8081-4eb4-a282-3cf60c11fad0.png)

After that, I read [this issue](https://github.com/teejee2008/timeshift/issues/313) that says you can create a valid `info.json` (by taking new snapshot) and replace it with the corrupted one. That's why I plan to make a new `info.json`.

The problem is that I'm on a live system (restore only mode) and unable to create new snapshots. I think I should make `info.json` by hand, but I'm not 100% sure what the content should be.

This is my present situation.

Thank you.

**Comment by wmutschl** [comment]
Yes the info.json can get corrupted sometimes, I still don't know why exactly, but don't worry as your snapshots and data are fine. Personally, I would not use timeshift in your case to restore your system, but do it manually. The steps would be something like this (I am not at my computer right now, so the paths might be slightly different).

Boot into the live system and uncrypt your luks partition and mount the top-level root of your btrfs partition:
```
sudo cryptsetup luksOpen /dev/nvme0n1p3 cryptdata
sudo mount -o subvolid=5 /dev/mapper/cryptdata /mnt
ls /mnt
```
This should output something like: `@ @home timeshift-btrfs` Your snapshots are in the folder `/mnt/timeshift-btrfs/snapshots/YYYY-MM-DD_HH-MM-SS`. 

Now first move broken subvolume @ away:
```
sudo mv /mnt/@ /mnt/@.bad
```
Next, create a new @ from a good snapshot:
```
sudo btrfs subvolume snapshot /mnt/timeshift-btrfs/snapshots/YYYY-MM-DD_HH-MM-SS/@ /mnt/@
```
Restart and all should be back to the way it was.

**Comment by naskya** [comment]
Thank you very much. My system is now fully restored. Also, I finally understand what timeshift is doing (I was too afraid to touch the contents of the snapshot :joy:).

Kind Regards.

**Comment by wmutschl** [comment]
Yes, Timeshift is just a GUI tool for the btrfs command, so it is not really necessary. Anyways, you should check whether timeshift creates new snapshots and either repair the info.json files or simply remove those snapshots.
