### ISSUE TITLE
POP!_OS 22.04 mount fails after install & fstab changes brick GDM

### ISSUE THREAD

**Issue by S0PEX** [wmutschl/mutschler.eu#35]
Hey,

I am currently trying to setup Pop OS LTS 22.04 and tried to follow your 21.04 and 21.10 guide and end up with the same issues.
Basically all steps work until the point where the os is installed and I would need to move the files to the sub volumes.
**When I just restart the OS the encryption etc. works fine and is indeed btrfs.**

**First Issue:**

Once the intaller is finished installing I am able to open the luks partition but not able to mount it.
```shell
$ cryptsetup luksOpen /dev/nvme1n1p6 cryptdata
# Enter passphrase for /dev/nvme1n1p6:
$ ls /dev/mapper
# control cryptdata data-root
$ mount -o subvolid=5,ssd,noatime,space_cache,commit=120,compress=zstd,discard=async /dev/mapper/data-root /mnt
mount: wrong fs type, bad option, bad superblock on /dev/mapper/data-root,
       missing codepage or helper program, or other error
 ```
When I just restart the os it boots finde and using `df -Th` shows that its indeed `btrfs`

**Second Issue:**

As I don't really need the snapshots I thought I will just skip the sub volumes then and just apply your `fstab` optimizations.
So once I am booted inside Pop-OS I execute:
```shell
$ sed -i 's/btrfs  defaults/btrfs  defaults,ssd,noatime,space_cache,commit=120,compress=zstd,discard=async/' /etc/fstab
$ sed -i 's/luks/luks,discard/' /etc/crypttab
```

Once I reboot I will stuck on the Password entry screen (the partition was already unlocked but the screen flashes once and then comes back with the login). When I then switch to terminal mode `Ctrl+Shift+F2` I can see the login-promt and login with my user.
When then trying to exit `/etc/fstab` I will get the error that the file is `read-only`, as root.

Has something changed with 22.04? It seems like only the Gnome Display Manager fails to start due to some mounting issues?
Did you maybe had a chance to apply your guide to 22.04?

Regards Artur

**Comment by everlanes** [comment]
I also ran into that issue.

New Pop!_OS seems to activate `space_cache=v2`. According to the man page, once Version 2 is activated you always have to use Version 2. The option `space_cache` defaults to Version 1. That is why the mount fails.

Solution: always use `space_cache=v2` or omit this option completely (it is redundant):

```
$ mount -o subvolid=5,ssd,noatime,space_cache=v2,commit=120,compress=zstd,discard=async /dev/mapper/data-root /mnt
```

and

```
$ sed -i 's/btrfs  defaults/btrfs  defaults,ssd,noatime,space_cache=v2,commit=120,compress=zstd,discard=async/' /etc/fstab
```

**Comment by wmutschl** [comment]
Hi, thanks for this solution, this is exactly what I would have proposed as well. I have uploaded a new guide (note that I am moving the guides to a new homepage mutschler.dev). I also ommit the commit, ssd and noatime mount options as the defaults of btrfs have become better with recent linux kernels and I do not notice any performance differences with or without these options, so I'd rather stick to the defaults and only add compress=zstd:1 and discard=async (even though discard=async will become the default for SSDs soon).
