### ISSUE TITLE
Manjaro page lost

### ISSUE THREAD

**Issue by noyannus** [wmutschl/mutschler.eu#37]
What happened to the Manjaro page (https://mutschler.eu/linux/install-guides/manjaro-btrfs/)?

"This site has moved to https://mutschler.dev" -- must have fallen off the truck...

**Comment by wmutschl** [comment]
That guide was based on the Architect installer of Manjaro, which is depreciated since a long time, so I removed the guide. By the way, Manjaro's defaults for btrfs installation are actually very sensible and great.

**Comment by noyannus** [comment]
Thanks for the info! And have a good Winter time!
