### ISSUE TITLE
[Suggestion] add note for grub-btrfs & read-only snapshots

### ISSUE THREAD

**Issue by noyannus** [wmutschl/mutschler.eu#8]
Suggestion: In the tutorials involving `grub-btrfs`, include a note that for _read-only_ snapshots "`/var/log` or even `/var` must be on a separate subvolume", see [here](https://github.com/Antynea/grub-btrfs#warning-booting-on-read-only-snapshots-can-be-tricky).

An unknown number of headaches will not happen. :)

**Comment by wmutschl** [comment]
Thanks! I will do so, once I update the guides for the new versions! I will keep this issue open to remind me of it.
